const Booking = {
  ALL_BIKES: 'ALL_BIKES',
  GET_BIKE_ID: 'GET_BIKE_ID',
  ONE_BIKE: 'ONE_BIKE',
  ALL_RESERVATIONS: 'ALL_RESERVATIONS',
  ONE_RESERVATION: 'ONE_RESERVATION',
  CREATE_RESERVATION: 'CREATE_RESERVATION',
};
export default Booking;
